apiVersion: v1
kind: Service
metadata:
  name: bee-hive-service
spec:
  selector:
    app: bee-hive
  ports:
    - protocol: TCP
      port: 80       # Service port
      targetPort: 80  # Container port
  type: NodePort  # Exposes the service externally