apiVersion: v1
kind: Service
metadata:
  name: patient-enrolment-service
spec:
  selector:
    app: patient-enrolment
  type: NodePort
  ports:
    - port: 6002
      targetPort: 6002
      nodePort: 31002
