apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth
  labels:
    app: user-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-auth
  template:
    metadata:
      labels:
        app: user-auth
    spec:
      containers:
        - name: user-auth
          image: sugashinikaliappan/user_auth:latest
          ports:
            - containerPort: 6000
