name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        options: >-
          --replSet rs0
          --oplogSize 128
          --port 27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set Environment Variables
        run: |
          echo "DATABASE_URL=mongodb+srv://devopsbhwuser:devopsbhwuser@cluster0.aj515.mongodb.net/HospitalStaffDetails?retryWrites=true&w=majority&appName=Cluster" >> $GITHUB_ENV
          echo "JWT_SECRET=myabcd123" >> $GITHUB_ENV
          echo "PORT=5000" >> $GITHUB_ENV

      - name: Initialize MongoDB Replica Set
        run: |
          sleep 5 # Wait for MongoDB to start
          mongosh --eval "rs.initiate()"

      - name: Install dependencies
        run: |
          cd user_authentication
          npm ci

      - name: Generate Prisma Client
        run: |
          cd user_authentication
          npx prisma generate

      - name: Run Tests
        run: |
          cd user_authentication
          npm test

      - name: Build Docker image
        run: docker build -t bee_hive .
