name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 5000:5000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Wait for MongoDB to Start
        run: sleep 10  # ✅ Ensures MongoDB is fully initialized

      - name: Install dependencies
        run: |
          cd user_authentication
          npm ci

      - name: Generate Prisma Client
        run: |
          cd user_authentication
          npx prisma generate

      - name: Run Tests
        run: |
          cd user_authentication
          npm test

      - name: Build Docker image
        run: docker build -t bee_hive .
